# Generated by Django 6.0 on 2025-12-10 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartChamaV1', '0002_chamamember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymenyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_request_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartChamaV1.chamamember')),
            ],
        ),
    ]
