# Generated by Django 4.2.27 on 2025-12-10 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SmartChamaV1', '0003_paymenyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_request_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='chamamember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='PaymenyHistory',
        ),
        migrations.AddField(
            model_name='payments',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartChamaV1.chamamember'),
        ),
    ]
