# Generated by Django 6.0 on 2025-12-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartChamaV1', '0004_payments_alter_chamamember_id_delete_paymenyhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamamember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
